workspace = { members = ["to_run"] }
[package]
name = "run_cmd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.1"
shutil = "0.1.2"
